services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DB_URL=postgres://app:app@db:5432/app?sslmode=disable
      - BOXOFFICE_URL=${BOXOFFICE_URL}
      - BOXOFFICE_API_KEY=${BOXOFFICE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: